braindigit_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: BraindigitUserBundle:Default:index }

braindigit_user_list:
    path:     /admin/users
    defaults: { _controller: BraindigitUserBundle:User:index }
