braindigit_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: BraindigitUserBundle:Default:index }

braindigit_user_list:
    path:     /admin/users
    defaults: { _controller: BraindigitUserBundle:Backend/User:index}
    options:
        expose: true

braindigit_user_form:
    path:     /admin/user/form/{id}
    defaults: { _controller: BraindigitUserBundle:Backend/User:form, id:0 }
    requirements:
        id: \d+

braindigit_user_delete:
    path:     /admin/user/delete
    defaults: { _controller: BraindigitUserBundle:Backend/User:delete }
    methods:  [POST]