Braindigit\UserBundle\Entity\User:
  properties:
    fullname:
      - NotBlank: { message: "braindigit_user.fullname.blank" }
      - Length:
          min: 5
          max: 200
          minMessage: "braindigit_user.fullname.short"
          maxMessage: "braindigit_user.fullname.long"
    username:
      - Length:
          min: 3
          max: 15
    plainPassword:
      - Length:
          min: 5
          minMessage: ~