Braindigit\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: Braindigit\UserBundle\Entity\UserRepository
    properties:
        fullname:
            - NotBlank: ~
            - Length:
                min: 5
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        fullname:
            type: string
            length: 255

    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id