Braindigit\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: Braindigit\UserBundle\Entity\UserRepository
    properties:
        fullname:
            - NotBlank: ~
            - Length:
                min: 5
        profile_picture_file:
            - File:
                maxSize: 1M
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        fullname:
            type: string
            length: 255
        profile_picture:
            type: string
            length: 255
            nullable: TRUE

    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        postRemove: [removeUpload]