Braindigit\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: Braindigit\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        fullname:
            type: string
            length: 255
        profile_picture:
            type: string
            length: 255
            nullable: TRUE
        updatedOn:
            type: datetime
            nullable: TRUE
            column: updated_on
        registeredOn:
              type: datetime
              nullable: TRUE
              column: registered_on

    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
                        onDelete: CASCADE
    lifecycleCallbacks:
        prePersist: [setRegisteredOnValue, preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        postRemove: [removeUpload]