NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

braindigit_api:
    resource: "@BraindigitApiBundle/Resources/config/routing.yml"
    prefix:   /api

site_welcome:
    path:     /
    defaults: { _controller: BraindigitHomepageBundle:Frontend/Default:index }

braindigit_homepage:
    resource: "@BraindigitHomepageBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_common:
    resource: "@BraindigitCommonBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_admin_main:
    path:  /admin
    defaults: { _controller: FOSUserBundle:Security:login }

braindigit_admin_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

braindigit_admin_check:
    path:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

braindigit_admin_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

braindigit_event:
    resource: "@BraindigitEventBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_category:
    resource: "@BraindigitCategoryBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_page:
    resource: "@BraindigitPageBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_user:
    resource: "@BraindigitUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
