braindigit_event:
    resource: "@BraindigitEventBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_category:
    resource: "@BraindigitCategoryBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_page:
    resource: "@BraindigitPageBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_user:
    resource: "@BraindigitUserBundle/Resources/config/routing.yml"
    prefix:   /

braindigit_demo:
    resource: "@BraindigitDemoBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
