Braindigit\CategoryBundle\Entity\Category:
    type: entity
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    table: category
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        bundle:
            type: string
            length: 255
        status:
            type: boolean
            nullable: false
        ownerId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: owner_id
        createdOn:
            type: date
            nullable: false
            comment: ''
            column: created_on
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
    manyToOne:
        parent:
            targetEntity: Braindigit\CategoryBundle\Entity\Category
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Braindigit\CategoryBundle\Entity\Category
            mappedBy: parent
            orderBy:
                lft: ASC