Braindigit\PageBundle\Entity\Page:
    type: entity
    table: page
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        tags:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        image:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        status:
            type: boolean
            nullable: false
            comment: ''
        ownerId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: owner_id
        publishedOn:
            type: datetime
            nullable: false
            comment: ''
            column: published_on
        createdOn:
            type: date
            nullable: false
            comment: ''
            column: created_on
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]