#services:
#    braindigit_page.example:
#        class: Braindigit\PageBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    braindigit_page.db.table_prefix: bd_

services:
    braindigit_page.tblprefix_subscriber:
        class: Braindigit\PageBundle\Subscriber\TablePrefixSubscriber
        arguments: [%braindigit_page.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
    sonata.admin.post:
        class: Braindigit\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Page" }
        arguments:
            - ~
            - Braindigit\PageBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [BraindigitPageBundle]]